name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # غيّرها إذا كان فرعك مختلفًا

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create env.json file
        run: |
          echo '{ "apiKey": "Bearer ${{ secrets.OPENAI_API_KEY }}" }' > env.json
          cat env.json  # تحقق من المحتوى في الـ logs

      - name: Copy env.json to public folder
        run: cp env.json ./public/

      - name: Setup Node.js
        uses: actions/setup-node@v18
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build  # استخدم الأمر المناسب لمشروعك

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: public  # المسار الذي يحتوي على `index.html`
